name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # sets up .NET Core SDK 6.0.x
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x

         # Install dotnet wasm buildtools workload
        - name: Install .NET WASM Build Tools
          run: dotnet workload install wasm-tools


        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish NaziLife/NaziLife.csproj -c Release -o release --nologo

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
            BRANCH: gh-pages
            FOLDER: release/wwwroot
            # TODO uncomment the following line if you have a custom domain name
            cname: nazi.life
